### PR TITLE
mdbClient: improve sql statement in Grant/Revoke

### LINKED ISSUE #55: [Bug] Grant controller fails to grant/revoke privileges if database name contains dashes
**Describe the bug**

Given the following CRs
```
---
apiVersion: mariadb.mmontes.io/v1alpha1
kind: Database
metadata:
  name: ak-test
spec:
  mariaDbRef:
    name: mariadb
  characterSet: utf8
  collate: utf8_general_ci
---
apiVersion: mariadb.mmontes.io/v1alpha1
kind: User
metadata:
  name: ak-test-user
spec:
  mariaDbRef:
    name: mariadb
  passwordSecretKeyRef:
    name: ak-test-user
    key: password
---
apiVersion: mariadb.mmontes.io/v1alpha1
kind: Grant
metadata:
  name: ak-test-grant
spec:
  mariaDbRef:
    name: mariadb
  privileges:
    - "ALL"
  database: "ak-test"
  table: "*"
  username: ak-test-user
  grantOption: false
---
apiVersion: v1
kind: Secret
metadata:
  name: ak-test-user
data:
  password: NjRiYzJlZWYyYzgyN2ZlY2JmYjFiYzMzOWIyMTFkZTQ=
```

the controller fails to add grant with the following error

```
error reconciling in TemplateReconciler: error creating ak-test-grant: 1 error occurred:\n\t* error granting privileges in MariaDB: Error 1064: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '-test.* TO 'ak-test-user'@'%' WITH GRANT OPTION'
```

**Expected behaviour**

I expect the controller to successfully assign the grant

**Environment details**:
- Kubernetes version: 1.25.
- mariadb-operator version: mmontes11/mariadb-operator:v0.0.9
- Install method: helm
- Install flavour: recommended

### PR DESCRIPTION
**Pull request by macno**
Fixes #55

### CODE REVIEW

**Comment by macno** [comment]
@mmontes11 any idea why the CI is failing? Do I have to do something on my side?

**Comment by mmontes11** [comment]
Hey @macno !

LGTM! 🚀 
Thanks for contributing to `mariadb-operator`

> any idea why the CI is failing? Do I have to do something on my side?

It's something on our side, don't worry I'm looking into it 👀

**Comment by mmontes11** [comment]
Hey @macno ! 

The tests are running now but they are failing because now we are escaping the `*`:
- https://github.com/mmontes11/mariadb-operator/blob/main/controllers/grant_controller_test.go#L89..L90

Both cases should work, `*` and literal tables/databases/users with dashes, so I suggess we can wrap them with this function:
```golang
func escape(s string) string {
	if s == "*" {
		return s
	}
	return fmt.Sprintf("`%s`", s)
}
```
Does this makes sense?

It would be awesome if you could add some tests covering this tests cases here:
- https://github.com/mmontes11/mariadb-operator/blob/main/controllers/grant_controller_test.go

Thanks a lot and sorry for the issues with the CI! 🙏🏻 🙇🏻

**Comment by macno** [comment]
> Hey @macno !
> 
> The tests are running now but they are failing because now we are escaping the `*`:
> 
> * https://github.com/mmontes11/mariadb-operator/blob/main/controllers/grant_controller_test.go#L89..L90
> 
> Both cases should work, `*` and literal tables/databases/users with dashes, so I suggess we can wrap them with this function:
> 
> ```go
> func escape(s string) string {
> 	if s == "*" {
> 		return s
> 	}
> 	return fmt.Sprintf("`%s`", s)
> }
> ```
> 
> Does this makes sense?
> 

I'm checking
> It would be awesome if you could add some tests cases covering this here:
> 
Ok, on it

> * https://github.com/mmontes11/mariadb-operator/blob/main/controllers/grant_controller_test.go
> 
> Thanks a lot and sorry for the issues with the CI! 🙏🏻 🙇🏻

no problem

**Review by mmontes11 — APPROVED** [review]
Thanks for your contribution @macno !

**Pull request merged**
